### ISSUE TITLE
Allow direct access to ga.Service and ga.State

### ISSUE THREAD

**Issue by LubosD** [saml-dev/gome-assistant#2]
Hi,

I've started using your library to develop a power routing app, which routes power around the home to maximize PV production consumption. Thanks a lot for making it!

Now a small problem I have is that the only official way to get access to `ga.Service` and `ga.State` is by receiving them in the callback. That's fine and I understand why you made this design choice.

The problem is, as my app grows more complex, I would have to pass these pointers from the event receiver further into the handling logic, which then makes the codebase very tightly coupled to your library.

For example, I have a `SmartMeter` struct that receives and processes per-phase grid power measurements and emits the sum value into a callback:

```
OnGridPower func(watts int)
```

But without the ability to call `GetService()` on `ga.App`, I'd have to extend this callback with the `ga.Service` pointer, which feels just wrong :-/

Would you consider adding `GetService()` and `GetState()` to `ga.App`?

**Comment by saml-dev** [comment]
Short answer: Sure, I don't have a problem with adding those two getters.

Long answer: I think your strategy ends up makes your app (which sounds cool btw!) _more_ coupled to GA. If you ever changed GA to a different library, you'd have to go everywhere you use `GetService` or `GetState` and refactor.

If decoupling is important to you, perhaps a better way would be to create your own interface for calling services and/or retrieving state, then using GA to implement it. Then if you ever swap out GA in the future for something else, you only have to update your implementation and all your business logic is untouched.

Something like 
```
OnGridPower func(watts int, sg StateGetter)
```
where StateGetter is your custom interface that uses GA under the hood. Then you can set up your contracts as needed for your business logic.

All that to say, yes feel free to add those getters 😂
